language: python

python:
  - "2.7"
  - "3.6"

install:
  - pip install boto
  - pip install codecov
  - pip install coverage
  - pip install six

script:
  - coverage run -m unittest discover

after_success:
  - codecov